### PR TITLE
Enabling search on site

### PR DESCRIPTION
**Pull request by ashleytqy**
This PR addresses https://github.com/ml5js/ml5js.github.io/issues/4

Search is now enabled!

screen shot 2018-03-06 at 12 47 08 pm

### CODE REVIEW

**Comment by cvalenzuela** [comment]
awesome! thanks @ashleytqy

the keys don't need to be registered with anything specific?

**Comment by ashleytqy** [comment]
nope! they don't according to the docs – https://community.algolia.com/docsearch/ :

> You don’t need to configure any settings or even have an Algolia account.
> We take care of all of this automatically to ensure the best documentation search experience.

**Comment by cvalenzuela** [comment]
great! thanks

**Comment by shiffman** [comment]
Thank you @ashleytqy! Just curious, how did you discover the project? (Feel free to drop me a note at [the e-mail on this page](https://tisch.nyu.edu/about/directory/itp/1984778605).)

**Pull request merged**
