### PR TITLE
Data and training

### PR DESCRIPTION
**Pull request by cvalenzuela**
I'm updating the data an training sections of the website to match the new api.
I've also separated the part @handav wrote about data into different sections. I think this makes content more readable and sharable. 

I also wrote some introductions to the data and training sections and added a few extra sentences.

This looks like this in the left menu:

And I added a new section to the top menu:

### CODE REVIEW

**Review by shiffman — APPROVED** [review]
This is fantastic! I meant to just make minor edits, but ended up adding a whole section on transfer learning from the Adjacent article. @handav or @cvalenzuela feel free to make any comments or further changes and go ahead and merge if you are happy with it!

**Comment by handav** [comment]
Taking a look now!

**Comment by handav** [comment]
This looks amazing. Only tiny suggestion would be to be consistent with how you write 'dataset' (it's here as data-set, data set, and dataset). My suggestion is the joined word 'dataset'.

**Review by handav — COMMENTED** [review]
This looks amazing. Only tiny suggestion would be to be consistent with how you write 'dataset' (it's here as data-set, data set, and dataset). My suggestion is the joined word 'dataset'.

**Pull request merged**
