### PR TITLE
New version of the website

### PR DESCRIPTION
**Pull request by cvalenzuela**
PR to update the website with the newest changes.
Most of the updates here are just style. This site is still running on ml5 0.0.4 and is missing docs for the newest methods

Not ready to merge yet

### CODE REVIEW

**Comment by yining1023** [comment]
I finished the image classification drag drop iframe example (https://ml5js.github.io/ml5-homepage-demo/).
I added a file uploader, made the image responsive, hide the whole iframe when window.width < 200px, added font and some other styles.
It looks like this on the website. I tested it with uploading images in different size, uploading non-image file. Please let me know if you notice any responsiveness issues.
screen shot 2018-06-06 at 9 29 36 pm


We are very close! please let me know if there is anything that I can do.

**Comment by cvalenzuela** [comment]
Just so what will @handav will show tomorrow matches the current version, I have just updated the site to the new style! Looks great! nice work @matamalaortiz, @yining1023 and @shiffman!

This is merge in `master` but not in `source` yet

**Comment by matamalaortiz** [comment]
Pushed #44 to this branch.

**Comment by shiffman** [comment]
yahooooooo!

**Pull request merged**
