### PR TITLE
Design updates

### PR DESCRIPTION
**Pull request by matamalaortiz**
Minor Changes to the website (styles):

• A new component in the index to display the project title and example:
 - Added an example of Simple Image Classification in the home. (todo: replace the image with the code to the react highlighter syntax)

• Css changes in the documentation section. (Sidebar size and colors, Titles font family and .hljs styling) 

• Replaced cat for the Simple Image Classification example. We discuss with Cris the idea of display the other image for that example. The bird kind of looks better and also has 0.99 confidence.

### CODE REVIEW

**Comment by matamalaortiz** [comment]
not ready for merge. sending new commits soon.

**Comment by cvalenzuela** [comment]
I like where this is going! @matamalaortiz mention this was just a quick and dirty fix and that major redesign will come later. I think we could merge this just to show it tomorrow. @shiffman?

**Comment by shiffman** [comment]
Yes!

**Comment by matamalaortiz** [comment]
Still, I want to change some things regarding the example at the home page of this version. But at this point, I think is better after tomorrow. Yes! major changes will come!

**Pull request merged**
