### PR TITLE
Design updates

### PR DESCRIPTION
**Pull request by matamalaortiz**
This example image I added in the home was having some issues on different screen resolutions. I decided to get rid of it, I'll try a proper way for this with the react syntax highlighter and CSS instead of adding a fixed image.

### CODE REVIEW

**Comment by shiffman** [comment]
But I love it so! (Maybe it's ok for showing on desktop only tomorrow?)

**Comment by shiffman** [comment]
One small thing (though I don't know it really matters) is that the code doesn't exactly match the image since the "I guess this is a. . " is not part of the `console.log`).

**Comment by matamalaortiz** [comment]
Sure, we can leave it for tomorrow.

Would something like this (p5 style) make more sense, as it is in the examples? 

screen shot 2018-03-14 at 9 27 07 pm

**Comment by matamalaortiz** [comment]
without the "s"
screen shot 2018-03-14 at 9 44 25 pm

**Comment by shiffman** [comment]
Looks great! I think the `console.log` is actually good for simplicity but I realize I'm now trying to have it both ways. We could make what's below more "data" like and show a JSON snippet?

Also, this is also a separate discussion but I'm wondering if it's a little odd to say "I guess. . ." As if the model is a person. And also, this should probably use `ModelNet` instead of `SqueezeNet`?

But really I wouldn't worry too much about this for tomorrow, it's great!

**Comment by cvalenzuela** [comment]
@matamalaortiz, should we close this? I think the new design will modify all of this, no?

**Comment by matamalaortiz** [comment]
That's right, the new design is including this fix. Let's close this.

**Pull request closed without merging**
